In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
a2 = np.array([6,7,8,9,10])
print(a1 + a2)

[ 7  9 11 13 15]


In [6]:
print(a1.shape)
print(a2.shape)

(5,)
(5,)


In [7]:
a3 = np.array([[11,12,13,14],[15,16,17,18]] )
print(a3)
print(a3.shape)

[[11 12 13 14]
 [15 16 17 18]]
(2, 4)


In [9]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


In [11]:
a4 = np.array([[11,12.2,13,14],[15,16,17,18]] )
print(a4)
print(a4.shape)
print(a4.dtype)

[[11.  12.2 13.  14. ]
 [15.  16.  17.  18. ]]
(2, 4)
float64


In [12]:
a5 = np.array([[11,12.2,13,14],[15,'HELLO',17,18]] )
print(a5)
print(a5.shape)
print(a5.dtype)

[['11' '12.2' '13' '14']
 ['15' 'HELLO' '17' '18']]
(2, 4)
<U32
