In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
a2 = np.array([6,7,8,9,10])
print(a1 + a2)

# "normal" Python lists work different in terms addition 
print([1,2,3,4,5] + [6,7,8,9,10])

[ 7  9 11 13 15]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [7]:
print(a1.shape)
print(a2.shape)

(5,)
(5,)


In [8]:
a3 = np.array([[11,12,13,14],[15,16,17,18]] )
print(a3)
print(a3.shape)

[[11 12 13 14]
 [15 16 17 18]]
(2, 4)


In [9]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


In [10]:
a4 = np.array([[11,12.2,13,14],[15,16,17,18]] )
print(a4)
print(a4.shape)
print(a4.dtype)

[[11.  12.2 13.  14. ]
 [15.  16.  17.  18. ]]
(2, 4)
float64


In [14]:
a5 = np.array([[11,12.2,13,14],[15,'16',17,18]] )
print(a5)
print(a5.shape)
print(a5.dtype)

[['11' '12.2' '13' '14']
 ['15' '16' '17' '18']]
(2, 4)
<U32


In [15]:
print(a4+2)

[[13.  14.2 15.  16. ]
 [17.  18.  19.  20. ]]


In [16]:
print(a5+2)

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

In [23]:
# you cannot change the type of an element
a = np.array([[1,2,3], [3,6,9], [2,4,6]])
print(a)
print(a.dtype)
a[1][2] = 10
print(a)
a[1][2] = 12.5  # this works but will cast the float to int
print(a)
a[1][2] = '19'  # this works but will cast the str to int
print(a)
a[1][2] = 'HELLO'  # this does not work (cast not possible)
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]
int32
[[ 1  2  3]
 [ 3  6 10]
 [ 2  4  6]]
[[ 1  2  3]
 [ 3  6 12]
 [ 2  4  6]]
[[ 1  2  3]
 [ 3  6 19]
 [ 2  4  6]]


ValueError: invalid literal for int() with base 10: 'HELLO'

In [26]:
a = np.array([[1,2,3], [3,6,9], [2,4,6]])

print(a[0])
print(a[0][2])
print(a[0, 2])

[1 2 3]
3
3


In [30]:
print(a)
print(a[1, 1:3])
print(type(a[1, 1:3]))

[[1 2 3]
 [3 6 9]
 [2 4 6]]
[6 9]
<class 'numpy.ndarray'>
