In [1]:
import numpy as np

### arange

In [6]:
np.arange(0, 10, 3)  # start, stop, step

array([0, 3, 6, 9])

In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
np.arange(0, 10, 3, dtype=float)  # usage of explicit type

array([0., 3., 6., 9.])

### linspace

In [11]:
np.linspace(0, 5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [12]:
np.linspace(0, 5, num=10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.linspace(0, 5, num=10, endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [15]:
t = np.linspace(0, 5, num=10, endpoint=False, retstep=True)
print(t)
print(t[0])
print("Step size: {}".format(t[1]))

(array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]), 0.5)
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
Step size: 0.5


### matrix generation

In [19]:
print(np.diag([1,3,8]))
print(np.diag([1,3,8, 19]))
print(type(np.diag([1,3,8, 19])))

[[1 0 0]
 [0 3 0]
 [0 0 8]]
[[ 1  0  0  0]
 [ 0  3  0  0]
 [ 0  0  8  0]
 [ 0  0  0 19]]
<class 'numpy.ndarray'>


### ones and zeros

In [21]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [24]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### random numbers

In [26]:
# uniform distribution
np.random.rand(3,2)

array([[0.61040658, 0.09159012],
       [0.01530262, 0.91243336],
       [0.71390052, 0.05746503]])

In [42]:
# draw from standard normal distribution
np.random.randn(3,2)

array([[-0.28755473, -0.9668855 ],
       [-0.63895638,  1.28935758],
       [ 0.69350174,  0.91691631]])