In [1]:
import numpy as np

In [6]:
# use the "normal" constructor - not recommended
a1 = np.ndarray(shape=(4,), dtype=int, order='F')
a1[0] = 1
a1[1] = 2
a1[2] = 3
a1[3] = 4
print(a1)

[1 2 3 4]


In [7]:
# recommended: use creation from existing data  
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

In [9]:
a1 + a2

array([ 6,  8, 10, 12])

In [10]:
print(id(a1))
print(id(a2))
print(id(a1 + a2))

1897604540896
1897604540976
1897604542176


In [11]:
a1 - a2

array([-4, -4, -4, -4])

In [14]:
a1 / a2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [15]:
a1 * a2

array([ 5, 12, 21, 32])

In [18]:
a3 = np.array([[1,2,3,4], [1,2,3,4], [1,2,3,4]])
print(a3)
print(a3.shape)
a4 = np.array([5,6,7,8])
print(a4)
print(a4.shape)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
(3, 4)
[5 6 7 8]
(4,)


In [19]:
a3 + a4

array([[ 6,  8, 10, 12],
       [ 6,  8, 10, 12],
       [ 6,  8, 10, 12]])

In [20]:
a3.dot(a4)

array([70, 70, 70])

In [24]:
print(a3.shape)
print(a3.transpose())
print(a3.transpose().shape)

(3, 4)
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
(4, 3)
