In [3]:
import numpy as np

## Task 1

Task: Create a vector of size 10 with values ranging from 0 to 1, both excluded. Print the vector.

Approach: use the generator function linspace 

See: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html

In [11]:
# we'll use the generator function linspace
a = np.linspace(0, 1, 10)  # start and stop are by default included

print(a)
print("-----------------------")

b = np.linspace(0, 1, 12)  # start and stop are by default included
print(b)
print("-----------------------")

c = b[1:-1]
print(c)
print("-----------------------")

d = np.linspace(0, 1, 11, endpoint=False )
print(d)

print("-----------------------")
e = d[1:]
print(e)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
-----------------------
[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
-----------------------
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
-----------------------
[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]
-----------------------
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## Task 2
Task: Create a random vector of size 10 and sort it in place. Print the vector before and after sorting

Approach: use np.random and the array-method sort()

See: https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.ndarray.sort.html#numpy.ndarray.sort

In [33]:
a = np.random.rand(10)
print("Before sort (a):{}".format(a))
b = np.sort(a)  # if you use np.sort you get a copy and not an in-place sorting!
print("After np.sort (b):{}".format(b))
print("After np.sort (a):{}".format(a))

a.sort()
print("After ndarray-method sort (a):{}".format(a))


Before sort (a):[0.22947736 0.95587172 0.21298876 0.4630656  0.33599435 0.69805888
 0.30336094 0.25053201 0.02254588 0.87873958]
After np.sort (b):[0.02254588 0.21298876 0.22947736 0.25053201 0.30336094 0.33599435
 0.4630656  0.69805888 0.87873958 0.95587172]
After np.sort (a):[0.22947736 0.95587172 0.21298876 0.4630656  0.33599435 0.69805888
 0.30336094 0.25053201 0.02254588 0.87873958]
After ndarray-method sort (a):[0.02254588 0.21298876 0.22947736 0.25053201 0.30336094 0.33599435
 0.4630656  0.69805888 0.87873958 0.95587172]


## Task 3
Tasks: Create two random NumPy-arrays A and B with values drawn from 0 and 1 and length 5 (use randint).
Check if the arrays are equal (i.e. all elements are equal). Also check if at least one element is equal.

Approach: use randint and the all-operator

See https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html

In [115]:
# get to knwo the randint
print(np.random.randint(10))  # draw a random number between 0 and 9
print(np.random.randint(5, 10)) # draw a random number between 5 and 9
print(np.random.randint(5, 10, 3)) # draw three times a random number between 5 and 9 and put them into an ndarray

0
8
[7 8 6]


In [201]:
a = np.random.randint(0, 2, 3)
b = np.random.randint(0, 2, 3)
print(a)
print(b)

comparison = a == b
print(comparison)
print(all(comparison))
print(any(comparison))

[0 1 0]
[0 1 1]
[ True  True False]
False
True
